name: rl
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - jupyterlab
  - gym
  - blackd
  - black-jupyter
  - jupytext
  - matplotlib
  - pip
  - pip:
    - procgen
